name: cmna
channels:
  - conda-forge
dependencies:
  - python=3.8
  - xarray
  - bokeh
  - selenium
  - firefox
  - geckodriver
  - matplotlib
  - pyviz::jupyter_panel_proxy
  - pyviz::holoviews
  - pyviz::panel